vpc_cidr            = "10.20.0.0/16"
public_subnet_cidr  = "10.20.1.0/24"
public_subnet_az    = "us-east-1a"
private_subnet_cidr = "10.20.2.0/24"
private_subnet_az   = "us-east-1b"
region              = "us-east-1"
instance_type       = "t2.small"
environment         = "dev"